server:
  port: 8090

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  # swagger2 문서 오류 때문에

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: {id}
    password: {password}


  jpa:             # JPA - DB 테이블 연동x
    show-sql: true # JPA SQL문 확인 가능(기본 true)
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true # SQL문 가독성을 높여주는 설정(기본 true)

logging:
  level:
    org.hibernate.SQL: info